package Modelos;
// Generated 18/08/2017 01:12:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String tipoDocumento;
     private long documento;
     private String nombre;
     private String apellido;
     private String telefono;
     private long codigo;
     private String estado;
     private Set vehiculos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String tipoDocumento, long documento, String nombre, String apellido, String telefono, long codigo, String estado) {
        this.tipoDocumento = tipoDocumento;
        this.documento = documento;
        this.nombre = nombre;
        this.apellido = apellido;
        this.telefono = telefono;
        this.codigo = codigo;
        this.estado = estado;
    }
    public Cliente(String tipoDocumento, long documento, String nombre, String apellido, String telefono, long codigo, String estado, Set vehiculos) {
       this.tipoDocumento = tipoDocumento;
       this.documento = documento;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.codigo = codigo;
       this.estado = estado;
       this.vehiculos = vehiculos;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public long getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(long documento) {
        this.documento = documento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set vehiculos) {
        this.vehiculos = vehiculos;
    }

    @Override
    public String toString() {
        return nombre+" "+apellido;
    }




} 


