package Modelos;
// Generated 18/08/2017 01:12:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Parqueo generated by hbm2java
 */
public class Parqueo  implements java.io.Serializable {


     private Integer idParqueo;
     private Espacioparqueo espacioparqueo;
     private Promociones promociones;
     private Vehiculo vehiculo;
     private String fechaIngreso;
     private String fechaSalida;
     private String horaIngreso;
     private String horaSalida;
     private Set tickets = new HashSet(0);

    public Parqueo() {
    }

	
    public Parqueo(Espacioparqueo espacioparqueo, Vehiculo vehiculo, String fechaIngreso, String fechaSalida, String horaIngreso, String horaSalida) {
        this.espacioparqueo = espacioparqueo;
        this.vehiculo = vehiculo;
        this.fechaIngreso = fechaIngreso;
        this.fechaSalida = fechaSalida;
        this.horaIngreso = horaIngreso;
        this.horaSalida = horaSalida;
    }
    public Parqueo(Espacioparqueo espacioparqueo, Promociones promociones, Vehiculo vehiculo, String fechaIngreso, String fechaSalida, String horaIngreso, String horaSalida, Set tickets) {
       this.espacioparqueo = espacioparqueo;
       this.promociones = promociones;
       this.vehiculo = vehiculo;
       this.fechaIngreso = fechaIngreso;
       this.fechaSalida = fechaSalida;
       this.horaIngreso = horaIngreso;
       this.horaSalida = horaSalida;
       this.tickets = tickets;
    }
   
    public Integer getIdParqueo() {
        return this.idParqueo;
    }
    
    public void setIdParqueo(Integer idParqueo) {
        this.idParqueo = idParqueo;
    }
    public Espacioparqueo getEspacioparqueo() {
        return this.espacioparqueo;
    }
    
    public void setEspacioparqueo(Espacioparqueo espacioparqueo) {
        this.espacioparqueo = espacioparqueo;
    }
    public Promociones getPromociones() {
        return this.promociones;
    }
    
    public void setPromociones(Promociones promociones) {
        this.promociones = promociones;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public String getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(String fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public String getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(String fechaSalida) {
        this.fechaSalida = fechaSalida;
    }
    public String getHoraIngreso() {
        return this.horaIngreso;
    }
    
    public void setHoraIngreso(String horaIngreso) {
        this.horaIngreso = horaIngreso;
    }
    public String getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(String horaSalida) {
        this.horaSalida = horaSalida;
    }
    public Set getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set tickets) {
        this.tickets = tickets;
    }




}


