package Modelos;
// Generated 18/08/2017 01:12:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private Integer idServicio;
     private String tipo;
     private long valor;
     private Set serviciostickets = new HashSet(0);

    public Servicio() {
    }

	
    public Servicio(String tipo, long valor) {
        this.tipo = tipo;
        this.valor = valor;
    }
    public Servicio(String tipo, long valor, Set serviciostickets) {
       this.tipo = tipo;
       this.valor = valor;
       this.serviciostickets = serviciostickets;
    }
   
    public Integer getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(Integer idServicio) {
        this.idServicio = idServicio;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public long getValor() {
        return this.valor;
    }
    
    public void setValor(long valor) {
        this.valor = valor;
    }
    public Set getServiciostickets() {
        return this.serviciostickets;
    }
    
    public void setServiciostickets(Set serviciostickets) {
        this.serviciostickets = serviciostickets;
    }

    @Override
    public String toString() {
        return tipo+"   "+valor;
    }




}


