package Modelos;
// Generated 18/08/2017 01:12:51 PM by Hibernate Tools 4.3.1



/**
 * Tarifas generated by hbm2java
 */
public class Tarifas  implements java.io.Serializable {


     private Integer idTarifas;
     private Parqueaderos parqueaderos;
     private String jornada;
     private int valorMinuto;
     private String tipoVehiculo;

    public Tarifas() {
    }

    public Tarifas(Parqueaderos parqueaderos, String jornada, int valorMinuto, String tipoVehiculo) {
       this.parqueaderos = parqueaderos;
       this.jornada = jornada;
       this.valorMinuto = valorMinuto;
       this.tipoVehiculo = tipoVehiculo;
    }
   
    public Integer getIdTarifas() {
        return this.idTarifas;
    }
    
    public void setIdTarifas(Integer idTarifas) {
        this.idTarifas = idTarifas;
    }
    public Parqueaderos getParqueaderos() {
        return this.parqueaderos;
    }
    
    public void setParqueaderos(Parqueaderos parqueaderos) {
        this.parqueaderos = parqueaderos;
    }
    public String getJornada() {
        return this.jornada;
    }
    
    public void setJornada(String jornada) {
        this.jornada = jornada;
    }
    public int getValorMinuto() {
        return this.valorMinuto;
    }
    
    public void setValorMinuto(int valorMinuto) {
        this.valorMinuto = valorMinuto;
    }
    public String getTipoVehiculo() {
        return this.tipoVehiculo;
    }
    
    public void setTipoVehiculo(String tipoVehiculo) {
        this.tipoVehiculo = tipoVehiculo;
    }




}


