package Modelos;
// Generated 18/08/2017 01:12:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ticket generated by hbm2java
 */
public class Ticket  implements java.io.Serializable {


     private Integer idTicket;
     private Parqueaderos parqueaderos;
     private Parqueo parqueo;
     private Serviciosticket serviciosticket;
     private Usuario usuario;
     private String fecha;
     private String hora;
     private long valorTiempo;
     private String observaciones;
     private long puntos;
     private String estado;
     private long precioTotal;

    public Ticket() {
    }

	
    public Ticket(Parqueaderos parqueaderos, Usuario usuario, String fecha, String hora, long valorTiempo, String observaciones, long puntos, String estado, long precioTotal) {
        this.parqueaderos = parqueaderos;
        this.usuario = usuario;
        this.fecha = fecha;
        this.hora = hora;
        this.valorTiempo = valorTiempo;
        this.observaciones = observaciones;
        this.puntos = puntos;
        this.estado = estado;
        this.precioTotal = precioTotal;
    }
    public Ticket(Parqueaderos parqueaderos, Parqueo parqueo, Serviciosticket serviciosticket, Usuario usuario, String fecha, String hora, long valorTiempo, String observaciones, long puntos, String estado, long precioTotal) {
       this.parqueaderos = parqueaderos;
       this.parqueo = parqueo;
       this.serviciosticket = serviciosticket;
       this.usuario = usuario;
       this.fecha = fecha;
       this.hora = hora;
       this.valorTiempo = valorTiempo;
       this.observaciones = observaciones;
       this.puntos = puntos;
       this.estado = estado;
       this.precioTotal = precioTotal;
    }
   
    public Integer getIdTicket() {
        return this.idTicket;
    }
    
    public void setIdTicket(Integer idTicket) {
        this.idTicket = idTicket;
    }
    public Parqueaderos getParqueaderos() {
        return this.parqueaderos;
    }
    
    public void setParqueaderos(Parqueaderos parqueaderos) {
        this.parqueaderos = parqueaderos;
    }
    public Parqueo getParqueo() {
        return this.parqueo;
    }
    
    public void setParqueo(Parqueo parqueo) {
        this.parqueo = parqueo;
    }
    public Serviciosticket getServiciosticket() {
        return this.serviciosticket;
    }
    
    public void setServiciosticket(Serviciosticket serviciosticket) {
        this.serviciosticket = serviciosticket;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public long getValorTiempo() {
        return this.valorTiempo;
    }
    
    public void setValorTiempo(long valorTiempo) {
        this.valorTiempo = valorTiempo;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public long getPuntos() {
        return this.puntos;
    }
    
    public void setPuntos(long puntos) {
        this.puntos = puntos;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public long getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(long precioTotal) {
        this.precioTotal = precioTotal;
    }




}


