package Modelos;
// Generated 18/08/2017 01:12:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String tipoDocumento;
     private int documento;
     private String nombre;
     private String apellido;
     private String fechaNacimiento;
     private String email;
     private int celular;
     private String direccion;
     private String estado;
     private String tipo;
     private Set tickets = new HashSet(0);
     private Set parqueaderoses = new HashSet(0);
     private Set serviciostickets = new HashSet(0);
     private Set turnos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String tipoDocumento, int documento, String nombre, String apellido, String fechaNacimiento, String email, int celular, String direccion, String estado, String tipo) {
        this.tipoDocumento = tipoDocumento;
        this.documento = documento;
        this.nombre = nombre;
        this.apellido = apellido;
        this.fechaNacimiento = fechaNacimiento;
        this.email = email;
        this.celular = celular;
        this.direccion = direccion;
        this.estado = estado;
        this.tipo = tipo;
    }
    public Usuario(String tipoDocumento, int documento, String nombre, String apellido, String fechaNacimiento, String email, int celular, String direccion, String estado, String tipo, Set tickets, Set parqueaderoses, Set serviciostickets, Set turnos) {
       this.tipoDocumento = tipoDocumento;
       this.documento = documento;
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechaNacimiento = fechaNacimiento;
       this.email = email;
       this.celular = celular;
       this.direccion = direccion;
       this.estado = estado;
       this.tipo = tipo;
       this.tickets = tickets;
       this.parqueaderoses = parqueaderoses;
       this.serviciostickets = serviciostickets;
       this.turnos = turnos;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public int getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(int documento) {
        this.documento = documento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(String fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getCelular() {
        return this.celular;
    }
    
    public void setCelular(int celular) {
        this.celular = celular;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set tickets) {
        this.tickets = tickets;
    }
    public Set getParqueaderoses() {
        return this.parqueaderoses;
    }
    
    public void setParqueaderoses(Set parqueaderoses) {
        this.parqueaderoses = parqueaderoses;
    }
    public Set getServiciostickets() {
        return this.serviciostickets;
    }
    
    public void setServiciostickets(Set serviciostickets) {
        this.serviciostickets = serviciostickets;
    }
    public Set getTurnos() {
        return this.turnos;
    }
    
    public void setTurnos(Set turnos) {
        this.turnos = turnos;
    }

    @Override
    public String toString() {
        return nombre + "   " + documento;
    }




}


